### ISSUE TITLE
quotas & disk space usage info

### ISSUE THREAD

**Issue by suzhouclark** [Hexilee/tifs#2]
I am new for tifs. I build a test env for tifs. I have two questions.
1. Could you guide me how to set qutoas on tifs (maybe set some options when mount )? 
2. when I use df command, there is no disk space usage info, it display "-
![tifs](https://user-images.githubusercontent.com/3823093/124531271-bde35e80-de40-11eb-87e5-1ea4900aa308.png)
"

**Comment by Hexilee** [comment]
Oh, I think it's a wrong implementation of `statfs`, we should only set used space instead of size.

**Comment by Hexilee** [comment]
It seems we must set the total size, which is calculated by blocks and bsize. In this case, if we set the used space, the available space will always be zero (a confused behaviour).

**Comment by suzhouclark** [comment]
What about quotas on tifs (fuse) ?

**Comment by Hexilee** [comment]
We can have quotas, I can do that at this weekends. You are welcome to create a PR, just add a mount option and store it in `Meta`.

**Comment by Hexilee** [comment]
Should be implemented in #d816e44, please wait for v0.2.0 to use this feature.
